server = https://api.practicesoftwaretesting.com
brandsPath = /brands

# Contact List items
ContactListBaseURL= https://thinking-tester-contact-list.herokuapp.com
token= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2Q2NGE1MGZhZmY0NTAwMTNmY2JkY2IiLCJpYXQiOjE3NDI0ODk4MDB9.Xj13_oSptJ70hkXWpDsCU3S6i-3CtH38HOMrZz_Id30